[tool.poetry]
name = "blackboxopt"
version = "0.1.0"
description = "Surrogate models and active learning for scientific applications"
authors = ["Weslley S. Pereira <weslley.dasilvapereira@nrel.gov>"]
license = "GPL v3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^1.26.2"
matplotlib = "^3.8.2"
scipy = "^1.11.4"
pytest = "^7.4.3"
sphinx = "^7.2.6"
myst-parser = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
